version: "3.4"
services:

  php:
    build: ./docker/php
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/symfony-demo
    expose:
      - 9000

  db:
    image: mariadb:10.2.26
    restart: always
    environment:
      MYSQL_DATABASE: symfony_demo
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: symfony_demo_user
      MYSQL_PASSWORD: symfony_demo_password
      TZ: Europe/Prague
    ports:
      - '3307:3306'

  web:
    image: nginx:mainline-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./app:/symfony-demo
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '90:80'
